"""Add User model

Revision ID: 59348310ffbb
Revises: 8451a9cf6460
Create Date: 2025-01-18 22:19:00.988440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59348310ffbb'
down_revision = '8451a9cf6460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=22), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('uq_slug', type_='unique')

    op.drop_table('user')
    # ### end Alembic commands ###
