"""Add Mission model

Revision ID: 927677ed3598
Revises: 59348310ffbb
Create Date: 2025-01-24 02:27:38.389063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927677ed3598'
down_revision = '59348310ffbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('employer', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('employer_icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission')
    # ### end Alembic commands ###
